### ISSUE TITLE
draw.io link outdated

### ISSUE THREAD

**Issue by MiniGod** [duckyb/zmk-sweep#8]
I see you updated the layout image in the readme in 6b44977, but the draw.io link has not been updated.

I noticed for instance that the settings layer does not exist in the drawing on the link.

**Comment by duckyb** [comment]
@MiniGod Yes I am aware, however the point of the draw.io link is customization, so I don't think it's a big deal that it's not updated. It's just a base point to start editing and it has everything you need.

That being said I could consider updating it since I am not going to edit this firmware any longer.

**Comment by duckyb** [comment]
Should be fixed

**Comment by MiniGod** [comment]
Thanks. I was customizing this layout for my self, which is why I stumbled upon this.
Just out of curiosity, are you no longer updating this firmware because its perfect and doesn't need more updates or because you don't use it anymore (using something better?)?

**Comment by duckyb** [comment]
I am not updating it because I stopped using the Sweep in favor of the [Urchin](https://github.com/duckyb/urchin) that I designed.
It's firmware can be found at [zmk-urchin](https://github.com/duckyb/zmk-urchin) but it's still 99% the same as this one.
